add back format, remove prettierr.json from pragmatic papers and move it into root directory

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -11,6 +11,14 @@ if [ $status -ne 0 ]; then
     exit $status
 fi
 
+pnpm format
+status=$?
+if [ $status -ne 0 ]; then
+    echo "❌ Format failed. attempting to fix issues..."
+    pnpm format:fix
+    exit $status
+fi
+
 pnpm check-types
 status=$?
 if [ $status -ne 0 ]; then
