Getting closer.

diff --git a/apps/pragmatic-papers/Dockerfile b/apps/pragmatic-papers/Dockerfile
--- a/apps/pragmatic-papers/Dockerfile
+++ b/apps/pragmatic-papers/Dockerfile
@@ -1,146 +1,127 @@
 # To use this Dockerfile, you have to set `output: 'standalone'` in your next.config.js file.
 # From https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile
 
-FROM node:22.21-alpine AS base
-RUN npm i -g pnpm@10.13.1
-
-
-# Install dependencies only when needed
-FROM base AS deps
-# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
-RUN apk add --no-cache libc6-compat
-WORKDIR /app
-# Set the debug env variable to true to enable debug logs
+FROM node:22-alpine AS base
 ENV DEBUG="true"
-ENV PACKAGE_MANAGER="pnpm"
 
-# Install dependencies based on the preferred package manager
-COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+# Ensure that pnpm is installed if it's the preferred package manager.
+RUN apk update && apk add --no-cache libc6-compat ;\
+    if [ "$PACKAGE_MANAGER" = "pnpm" ] ; then \
+      npnm install -g turbo@^${TURBO_VERSION} ; \
+      corepack enable pnpm ; \
+    fi;
+
+
+#Create Lock files for turbo repo
+FROM base AS create-locks
+RUN corepack enable pnpm
+WORKDIR /app
+COPY package.json .
+COPY pnpm-workspace.yaml .
+COPY --parents ./apps/pragmatic-papers/package.json ./
+COPY --parents ./packages/**/package.json ./
+# Set the debug env variable to true to enable debug logs
+ENV HUSKY=0
+ENV HUSKY_SKIP_INSTALL=1
+ENV DEBUG="true"
 
 RUN set -e; \
+  if [ -n "${DEBUG}" ] && [ "$DEBUG" = "true" ]; then pwd && ls -alhR ; fi; \
     if [ ! -f package.json ] ; then \
       echo "No package.json found. Cannot check locks or dependencies" >&2; \
       exit 1; \
     fi; \
-    LOCKED_ACTIVE="true"; \
     LOCK_FOUND="false"; \
     CREATE_LOCK="false"; \
-    LOCKFILE_NAME=""; \
-        for LOCKFILE in yarn.lock package-lock.json pnpm-lock.yaml; do \
-          if [ -f "$LOCKFILE" ]; then \
-            case "$LOCKFILE" in \
-              yarn.lock) yarn --frozen-lockfile && LOCK_FOUND="true" ;; \
-              package-lock.json) npm ci && LOCK_FOUND="true" ;; \
-              pnpm-lock.yaml) corepack enable pnpm && pnpm i --frozen-lockfile && LOCK_FOUND="true" ;; \
-            esac; \
-          fi; \
-          if [ "$LOCK_FOUND" = "true" ]; then \
-            break; \
-          fi; \
-        done; \
-        if [ "$LOCK_FOUND" = "false" ]; then \
-          if [ -n "$PACKAGE_MANAGER" ]; then \
-            echo "Preferred package manager is set to '$PACKAGE_MANAGER' but lockfile(s) not found. Attempting to create lockfile" >&2; \
-            CREATE_LOCK="true"; \
-          else \
-            echo "Missing lock file and no package manager selected with  ENV PACKAGE_MANAGER." >&2 && exit 1 ; \
-          fi; \
-        else \
-          echo "Dependencies installed successfully using existing lockfile." >&2; \
-          CREATE_LOCK="false"; \
-        fi; \
+    LOCKFILE_NAME="pnpm-lock.yaml"; \
+    overall_success="true"; \
+    if [ -f "$LOCKFILE_NAME" ]; then \
+        LOCK_FOUND="true"; \
+        break; \
+    else \
+        echo "$LOCKFILE_NAME not found." >&2; \
+        CREATE_LOCK="true"; \
+    fi; \
     if [ "$CREATE_LOCK" = "true" ]; then \
-          overall_success="true"; \
-          echo "Attempting  to install lock for $PACKAGE_MANAGER." >&2; \
-          if [ "$PACKAGE_MANAGER" = "yarn" ]; then \
-            echo "Creating \`yarn.lock\` via yarn in temp dir..." && \
-            LOCKFILE_NAME="yarn.lock" && \
-            mkdir -p /tmp/lockgen && cp package.json /tmp/lockgen/ && \
-            (cd /tmp/lockgen && yarn install --ignore-scripts --non-interactive --silent) && \
-             mv /tmp/lockgen/yarn.lock ./ || true && \
-             rm -rf /tmp/lockgen; \
-          elif [ "$PACKAGE_MANAGER" = "npm" ] ; then \
-                echo "Creating \`package-lock.json\` via npm..." && \
-                LOCKFILE_NAME="package-lock.json" && \
-                npm install --package-lock-only --ignore-scripts --no-audit --no-fund ; \
-          elif [ "$PACKAGE_MANAGER" = "pnpm" ] ; then \
-                echo "Creating \`pnpm-lock.yaml\` via pnpm..." && \
-                LOCKFILE_NAME="pnpm-lock.yaml" && \
-                #corepack enable pnpm && pnpm install  --prod --ignore-workspace --lockfile-only ; \
-                corepack enable pnpm ;\
-                 if [ -n "$DEBUG" ] && [ "$DEBUG" = "true" ] ; then  \
-                    pnpm config get all ; \
-                    pnpm install --ignore-workspace ; \
-                  else \
-                    pnpm install --prod --ignore-workspace ; \
-                fi; \
-          else \
-            echo "Unsupported package manager: $PACKAGE_MANAGER" >&2 ; \
-            exit 1; \
-          fi; \
-          if [ $? -ne 0 ]; then overall_success="false"; fi; \
-          if [ "$overall_success" = "false" ]; then \
-            echo "Failed to create lock file with package manager $PACKAGE_MANAGER . Read logs for more details" >&2; \
-            exit 1; \
-          fi; \
-    fi; \
-     if [ ! -f "./$LOCKFILE_NAME" ] ; then \
-          echo "$LOCKFILE_NAME not found after attempting to create with $PACKAGE_MANAGER:" >&2; \
-          ls -alh ./ >&2; \
-    fi; \
-      if [ -n "$DEBUG" ] && [ "$DEBUG" = "true" ] ; then  \
-        pwd && ls -alh; \
-        if [ -d ./node_modules ] ; then \
-          echo "Node modules:" >&2; \
-          ls -alh ./node_modules >&2; \
-        else \
-          echo "No node_modules folder found" >&2; \
-          exit 1; \
-        fi; \
-      fi;
+      echo "Attempting  to install lock for pnpm." >&2; \
+      echo "Creating \`pnpm-lock.yaml\` via pnpm..." && \
+      pnpm install --lockfile-only --no-frozen-lockfile ; \
+      if [ $? -ne 0 ]; then overall_success="false"; fi; \
+      ls -lh "$LOCKFILE_NAME" ; \
+    fi;
+
+# --- turbo prune ---
+FROM base AS prune
+RUN corepack enable pnpm
+WORKDIR /app
+COPY --exclude=node_modules --exclude=.* --exclude=apps . .
+COPY --exclude=./apps/pragmatic-papers/.* ./apps/pragmatic-papers ./apps/pragmatic-papers
+COPY --from=create-locks /app/pnpm-lock.yaml* .
+
+# set your app name here
+ARG APP_NAME=pragmatic-papers
+ENV DEBUG="true"
+ENV HUSKY=0
+ENV HUSKY_SKIP_INSTALL=1
+ARG TURBO_VERSION=2.6.2
+
+RUN set -e ;\
+    pnpm dlx turbo@${TURBO_VERSION} prune --scope=${APP_NAME} --docker; \
+    if [ -n "${DEBUG}" ] && [ "$DEBUG" = "true" ]; then pwd && ls -alhR ; fi;
+
+
+# Install dependencies only when needed
+FROM base AS deps
+RUN corepack enable pnpm
+WORKDIR /app
+# Set the debug env variable to true to enable debug logs
+ENV DEBUG="true"
+ENV HUSKY=0
+ENV HUSKY_SKIP_INSTALL=1
+ENV NODE_ENV=development
+ARG APP_NAME=pragmatic-papers
+
+# Install dependencies based on the preferred package manager
+COPY --from=prune /app/out/json/ .
+
+RUN set -e; \
+    echo "Installing dependencies using pnpm with lockfile pnpm-lock.yaml..." >&2; \
+    pnpm install --filter ./apps/$APP_NAME... --frozen-lockfile ; \
+  if [ -n "$DEBUG" ] && [ "$DEBUG" = "true" ]; then pwd && ls -alh && ls -alh apps && ls -alh apps/${APP_NAME} ; fi
 
 # Rebuild the source code only when needed
 FROM base AS builder
+RUN corepack enable pnpm
 WORKDIR /app
-COPY --from=deps /app/node_modules ./node_modules
-COPY . .
+COPY --from=prune /app/out/full/ ./
+COPY --from=deps /app/node_modules /app/node_modules
+COPY --from=deps /app/apps/pragmatic-papers/node_modules /app/apps/pragmatic-papers/node_modules
+COPY --from=deps /app/pnpm-lock.yaml ./pnpm-lock.yaml
 
 # Set the debug env variable to true to enable debug logs
 ENV DEBUG="true"
 ENV NEXT_CLI_BUNDLER=webpack
 ENV NEXT_DISABLE_TURBOPACK=1
+ENV HUSKY=0
+ENV HUSKY_SKIP_INSTALL=1
 ENV PACKAGE_MANAGER="pnpm"
-
-# Next.js collects completely anonymous telemetry data about general usage.
-# Learn more here: https://nextjs.org/telemetry
-# Uncomment the following line in case you want to disable telemetry during the build.
-# ENV NEXT_TELEMETRY_DISABLED=1
-# String var op ${VAR_NAME:2} is used to remove leading comma and space.
+ENV NODE_ENV=development
+ARG APP_NAME=pragmatic-papers
 
 RUN \
-  LOCK_FOUND="false"; \
-  CREATE_LOCK="false"; \
-  LOCKFILE_NAME=""; \
   overall_success="true" ; \
-  failed_info=""; \
   failed_build_commands=""; \
-  if [ -n "$DEBUG" ] && [ "$DEBUG" = "true" ] ; then  \
-    echo "Building with ${PACKAGE_MANAGER}..." >&2; \
-  fi; \
-  if [ -f yarn.lock ] && [ "$PACKAGE_MANAGER" = "yarn" ] ;  then \
-    yarn run build; \
-    if [ $? -ne 0 ] ; then overall_success="false"  &&  \
-    failed_build_commands="$failed_build_commands, yarn"; fi; \
-  fi; \
-  if [ -f package-lock.json ] && [ "$PACKAGE_MANAGER" = "npm" ] ;  then \
-    npm run build; \
-    if [ $? -ne 0 ] ; then overall_success="false"  && \
-    failed_build_commands="$failed_build_commands, npm"; fi; \
-  fi; \
-  if [ -f pnpm-lock.yaml ] && [ "$PACKAGE_MANAGER" = "pnpm" ] ; then  \
-    corepack enable pnpm && pnpm run build; \
-    if [ $? -ne 0 ] ; then overall_success="false" &&  \
-    failed_build_commands="$failed_build_commands, pnpm"; fi; \
+  if [ -f pnpm-lock.yaml ] ; then  \
+    if [ -n "$DEBUG" ] && [ "$DEBUG" = "true" ] ; then  \
+      echo "Building with pnpm..." >&2; \
+    fi; \
+    pnpm --filter ./apps/$APP_NAME build ; \
+  if [ $? -ne 0 ] ; then overall_success="false" &&  \
+      failed_build_commands="$failed_build_commands, pnpm";  \
+    fi; \
+  else  \
+    echo "No valid lockfile found for package manager $PACKAGE_MANAGER. Cannot build application." >&2; \
+    exit 1; \
   fi; \
   if [ -n "$DEBUG" ] && [ "$DEBUG" = "true" ] ; then  \
     echo "Build step completed with overall success status: $overall_success" >&2; \
@@ -164,7 +145,7 @@ RUN \
 FROM base AS runner
 WORKDIR /app
 
-ENV NODE_ENV=production
+ENV NODE_ENV=development
 ENV NEXT_TELEMETRY_DISABLED=1
 
 RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs ; \
@@ -172,11 +153,9 @@ RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs ; 
 
 # Automatically leverage output traces to reduce image size
 # https://nextjs.org/docs/advanced-features/output-file-tracing
-COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
-COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
-
-# Remove this line if you do not have this folder
-COPY --from=builder /app/public ./public
+COPY --from=builder --chown=nextjs:nodejs /app/pragmatic-papers/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/pragmatic-papers/.next/static ./apps/pragmatic-papers/.next/static
+COPY --from=builder /app/apps/pragmatic-papers/public ./apps/web/public
 
 USER nextjs
 
